### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by kimshee16** [sudheer-ranga/aliexpress-product-scraper#36] opened 2023-02-16 16:12 UTC
I'm experiencing this when I bundle it using Browserify and use it to HTML:

bundle.alisavetools.js:183238 Uncaught TypeError: Cannot read properties of undefined (reading 'bind')
    at 1777.../common/Debug.js (bundle.alisavetools.js:183238:50)
    at o (bundle.alisavetools.js:1:265)
    at bundle.alisavetools.js:1:316
    at 1782.../common/Puppeteer.js (bundle.alisavetools.js:184562:29)
    at o (bundle.alisavetools.js:1:265)
    at bundle.alisavetools.js:1:316
    at Object.<anonymous> (bundle.alisavetools.js:183067:24)
    at Object.<anonymous> (bundle.alisavetools.js:183091:4)
    at 1775../node/Puppeteer.js (bundle.alisavetools.js:183091:17)
    at o (bundle.alisavetools.js:1:265)

**Comment by sudheer-ranga** [comment] 2023-12-06 18:55
@kimshee16 I have released a new version that fixes a lot of issues. Please update to the latest version v2.0.2 and try. If the issue is still happening, let me know.

**Comment by sudheer-ranga** [comment] 2023-12-26 20:58
Closing this issue for now. Feel free to reopen or create new issue if there is any problem with the latest update.

**Closed by sudheer-ranga** 2023-12-26 20:58 UTC
